# Generated by Django 4.2.1 on 2023-06-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
