# Generated by Django 4.2.1 on 2023-06-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='product.product'),
        ),
    ]
