# Generated by Django 4.2.1 on 2023-06-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
    ]
